### PR TITLE
Added new family to stml32 platform: stm32f3xx devices

### PR DESCRIPTION
**Pull request by Zaryob**
Get sources from [STMicroelectronics/STM32CubeF3](https://github.com/STMicroelectronics/STM32CubeF3/) repository.

Formatted tab style of stm32lib repository as mentioned in README.md file.

All devices provided with commit [86346f](https://github.com/STMicroelectronics/STM32CubeF3/commit/86346f63f25b859f93f9603837dcd5be28e8e7bf) in Stm32CubeF3 repository.

For clarify, Added Devices:
	* stm32f301x8
	* stm32f302x8
	* stm32f302xc
	* stm32f302xe
	* stm32f303x8
	* stm32f303xc
	* stm32f303xe
	* stm32f318xx
	* stm32f328xx
	* stm32f334x8
	* stm32f358xx
	* stm32f373xc
	* stm32f378xx
	* stm32f398xx

Signed-off-by: Suleyman Poyraz <zaryob.dev@gmail.com>

### CODE REVIEW

**Comment by dpgeorge** [comment]
Thanks for the contribution.

Did you intend to add support for the STM32F3xx series in MicroPython?  Are there particular F3 MCUs that you need support for?

**Comment by Zaryob** [comment]
> Thanks for the contribution.
> 
> Did you intend to add support for the STM32F3xx series in MicroPython? Are there particular F3 MCUs that you need support for?

Yeah Im intending support of STM32Fxxx series. There are all cards and specifications. I just add with way you provided in Readme file. 

All files are provided from STMicroelectronics github repository https://github.com/STMicroelectronics/STM32CubeF3 version 1.11.2

I quoted all family devices because if they will publish new devices, I can see which devices are absent in next releases then I can also add them.

I just wanna add this devices and I mentioned, because of supply conductivity.

**Comment by dpgeorge** [comment]
Note that adding the CMSIS and HAL code here is just part of adding support for STM32F3xx in MicroPython.  There's still quite a bit of work that needs to be done in MicroPython's stm32 port to make it all work.

**Comment by Zaryob** [comment]
If there is a way to testing it and make it fully working i can do it. But I dont know how it would be actually.

**Comment by Zaryob** [comment]
And also I can import other cards that i use if I get it.

**Comment by dpgeorge** [comment]
To get an idea of what's required to add support for a new MCU series, see here: https://github.com/micropython/micropython/pull/6911

**Comment by Zaryob** [comment]
> To get an idea of what's required to add support for a new MCU series, see here: [micropython/micropython#6911](https://github.com/micropython/micropython/pull/6911)

got it. Gonna test it then reply as nearly as possible.

**Comment by dpgeorge** [comment]
Closing because this MCU is old and we do not want to support it in MicroPython.  See further details at comment here: https://github.com/micropython/micropython/pull/6955#issuecomment-1326938967

**Pull request closed without merging**
