### PR TITLE
Import STM32Cube_FW_H7_V1.2.0 on 29-Dec-2017

### PR DESCRIPTION
**Pull request by iabdalkader**

### CODE REVIEW

**Comment by dpgeorge** [comment]
Thanks, it looks pretty good!

A couple of minor points:

1) It looks like you changed tab to space and removed non-ASCII chars, but there are a few remaining (eg line 498 of STM32H7xx_HAL_Driver/Inc/stm32h7xx_hal_fdcan.h).  That's probably because the `clean_code()` function provided in the README.md didn't cover this particular non-ASCII code.  Right?  I can fix this when merging.

2) The date in the commit message should be the date of release of the HAL by ST, *not* the date it's committed here.  It looks like the date of release by ST is 29 Dec 2017?

**Comment by iabdalkader** [comment]
Hi, yes I ran the clean_code() function in a loop on all files, didn't double check the output. Note you should add -f to rm tmp because the files are read only by default. Can you fix the clean_code function? I'll run it again and commit with the proper date (29-December-2017).

EDIT: add -f to mv tmp$$ so mv -f tmp$$

**Comment by dpgeorge** [comment]
> Can you fix the clean_code function?

Ok, now fixed by 6df2b092abcc2e05db754080a1fe784543de1295 to process more non-ASCII chars.  I also added a chmod 644 instead of mv -f.

**Comment by iabdalkader** [comment]
@dpgeorge Is this okay or should I redo the PR ?

**Comment by dpgeorge** [comment]
Ok, thanks for updating, now merged in acaf64eb1e6084495cebb716eac425fdef155b61.  I also applied a new tag: F4-1.16.0+F7-1.7.0+H7-1.2.0+L4-1.8.1

**Pull request closed without merging**
